transferring data

Fri Jul 16 14:55:23 EDT 2021
Finished transferring

Fri Jul 16 14:55:25 EDT 2021
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/zhan8425/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
Adas: Argument Parser Options
---------------------------------------------
    config              : /home/zhan8425/projects/def-msh/zhan8425/HistoKT/NewPretrainingConfigs/PCam_transformed-None-configAdas.yaml
    data                : /localscratch/zhan8425.22721098.0       
    output              : new-ImageNet-pretraining-output/None/PCam_transformed
    checkpoint          : new-ImageNet-pretraining-checkpoint/None/PCam_transformed
    resume              : None                                    
    pretrained_model    : ImageNet                                
    freeze_encoder      : 0                                       
    root                : .                                       
    save_freq           : 200                                     
    cpu                 : 0                                       
    gpu                 : 0                                       
    mpd                 : 0                                       
    dist_url            : tcp://127.0.0.1:23456                   
    dist_backend        : nccl                                    
    world_size          : -1                                      
    rank                : -1                                      
    color_aug           : None                                    
    norm_vals           : ImageNet                                
---------------------------------------------
Adas: Output dir new-ImageNet-pretraining-output/None/PCam_transformed does not exist, building
ImageNet
Adas: Notice: early stop will not be used as it was set to -1.0, training till completion
Adas: Experiment Configuration
---------------------------------------------
    dataset              PCam_transformed    
    network              ResNet18            
    optimizer            Adas                
    scheduler            None                
    level                L1                  
    color_kwargs         {'augmentation': 'None', 'distortion': 0.0}
    degree_of_rotation   45                  
    vertical_flipping    0.5                 
    horizontal_flipping  0.5                 
    horizontal_shift     0.1                 
    vertical_shift       0.1                 
    gaussian_blur        0                   
    kernel_size          9                   
    variance             0.1                 
    cutout               0                   
    n_holes              1                   
    cutout_length        16                  
    init_lr              0.03                
    early_stop_threshold -1.0                
    optimizer_kwargs     {'momentum': 0.9, 'weight_decay': 0.0005, 'beta': 0.98, 'linear': 0.0, 'gamma': 0.5, 'step_size': 25.0}
    scheduler_kwargs     {}
    p                    1                   
    start_trial          0                   
    n_trials             3                   
    num_workers          4                   
    max_epochs           250                 
    mini_batch_size      64                  
    loss                 cross_entropy       
    early_stop_patience  10                  
---------------------------------------------
Transforms:
Compose(
    RandomHorizontalFlip(p=0.5)
    RandomVerticalFlip(p=0.5)
    RandomAffine(degrees=[-45.0, 45.0], translate=(0.1, 0.1))
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)
Compose(
    ToTensor()
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
)
---------------------------------------------
Adas: Pytorch device is set to cuda
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 1392, in connect
    super().connect()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/http/client.py", line 915, in connect
    self.sock = self._create_connection(
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/adas/train.py", line 900, in <module>
    main(args)
  File "src/adas/train.py", line 859, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "src/adas/train.py", line 892, in main_worker
    training_agent.train()
  File "src/adas/train.py", line 403, in train
    self.reset(learning_rate)
  File "src/adas/train.py", line 343, in reset
    self.network = get_model(name=self.config["network"],
  File "/lustre03/project/6057785/zhan8425/HistoKT/src/adas/loader.py", line 59, in get_model
    loader = ModelLoader.load_from_ImageNet(model=name)
  File "/lustre03/project/6057785/zhan8425/HistoKT/src/adas/loader.py", line 17, in load_from_ImageNet
    model = resnet18(num_classes=1000, pretrained=True)
  File "/lustre03/project/6057785/zhan8425/HistoKT/src/adas/models/resnet.py", line 274, in resnet18
    return _resnet('resnet18', BasicBlock, [2, 2, 2, 2], pretrained, progress,
  File "/lustre03/project/6057785/zhan8425/HistoKT/src/adas/models/resnet.py", line 260, in _resnet
    state_dict = load_state_dict_from_url(model_urls[arch],
  File "/lustre03/project/6057785/zhan8425/HistoKT/ENV/lib/python3.8/site-packages/torch/hub.py", line 553, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/lustre03/project/6057785/zhan8425/HistoKT/ENV/lib/python3.8/site-packages/torch/hub.py", line 419, in download_url_to_file
    u = urlopen(req)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 1362, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx512/Core/python/3.8.2/lib/python3.8/urllib/request.py", line 1322, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>
